### PR TITLE
More Updates

### PR DESCRIPTION
**Pull request by SammySkycrafts**

### CODE REVIEW

**Review by chrisglobe — CHANGES_REQUESTED** [review]
E3CF are CFM powered E-3s (UK and French operated).
E3TF are turbofan powered E-3s as operated by the USA.

I think it's important that we differentiate between the two.

**Comment by SammySkycrafts** [comment]
Awaiting main db update as per #registration-database

**Comment by SammySkycrafts** [comment]
Mictronics db has been updated and changes made here to reflect this - Happy for this to be reviewed and merged.

**Comment by chrisglobe** [comment]
Thanks!

**Pull request merged**
